import turtle
turtle.hideturtle()
turtle.color("red")
turtle.begin_fill()
turtle.forward(100)
turtle.left(60)
turtle.forward(100)
turtle.left(60)
turtle.forward(100)
turtle.left(60)
turtle.forward(100)
turtle.left(60)
turtle.forward(100)
turtle.left(60)
turtle.forward(100)
turtle.left(60)
turtle.end_fill()
turtle.color("white")
turtle.penup()
turtle.left(90)
turtle.forward(65)
turtle.right(90)
turtle.pendown()
turtle.write("STOP", font=("Arial", 30, "normal"))
turtle.done()
